### ISSUE TITLE
Describe "--branch" parameter in README

### ISSUE THREAD

**Issue by andr2000** [xen-troops/build-scripts#38]

**Comment by andr2000** [comment]
Introduced in [this commit](https://github.com/xen-troops/build-scripts/commit/72e11d0ecedbb61bf600c7bd7c53be05554441c1)

**Comment by rshym** [comment]
Described by https://github.com/xen-troops/build-scripts/commit/b8743bece5d88648f07209fd52b0240fe9648c8e

**Comment by arminn** [comment]
It looks like it can be closed.
