### ISSUE TITLE
Add posibility to use upper yocto base local.conf for the product

### ISSUE THREAD

**Issue by al1img** [xen-troops/build-scripts#53]
It would be great if the script takes local.conf from meta-xt-prod.-xxx/doc folder as initial upper yocto local.conf. Some products require specific variables to be set in upper local.conf.

**Comment by iusyk** [comment]
fix: https://github.com/xen-troops/build-scripts/pull/54

**Comment by rshym** [comment]
Can we consider this issue as resolved as far as fix is merged?

**Comment by iusyk** [comment]
fixed
